settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: comment.hzxcaq.us.kg # unique identifier
    name: comment.hzxcaq.us.kg
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://comment.hzxcaq.us.kg/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: blog.hzxcaq.us.kg
    name: blog.hzxcaq.us.kg
    description: 'Built for anything connected to the Internet.'
    url: 'https://blog.hzxcaq.us.kg'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: img.hzxcaq.us.kg
    name: img.hzxcaq.us.kg
    url: 'https://img.hzxcaq.us.kg/'
    method: GET
    expectStatus: 200

  - id: status.hzxcaq.us.kg
    name: status.hzxcaq.us.kg
    url: 'https://status.hzxcaq.us.kg/'
    method: GET
    expectStatus: 200
