settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: blog.hxzcaq.ip-ddns.com
    name: blog.hxzcaq.ip-ddns.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://blog.hxzcaq.ip-ddns.com'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: img.hxzcaq.ip-ddns.com
    name: img.hxzcaq.ip-ddns.com
    url: 'https://img.hxzcaq.ip-ddns.com/favicon.jpeg'
    method: GET
    expectStatus: 200

  - id: https://comment.919497.xyz/
    name: https://comment.919497.xyz/
    description: 'Built for anything connected to the Internet.'
    url: 'https://comment.919497.xyz/'
    method: GET
    expectStatus: 200
    linkable: false # allows the title to be a link, default=true

